In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
X = train.drop('MedHouseVal', axis=1)
y = train['MedHouseVal']
test = test.fillna(test.mean())

In [4]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = X_train.fillna(X_train.mean())
X_val = X_val.fillna(X_val.mean())

In [11]:
lr = LinearRegression()
lr.fit(X_train, y_train)
# lr.coef_
# lr.intercept_
lr_val_pred = lr.predict(X_val)

print(f"MAE - {mean_absolute_error(y_val, lr_val_pred)}")
print(f"RMSE - {root_mean_squared_error(y_val, lr_val_pred)}")
print(f"MSE - {mean_squared_error(y_val, lr_val_pred)}")
print(f"R_squared - {r2_score(y_val, lr_val_pred)}")

MAE - 0.5442926093731731
RMSE - 0.7481548812164108
MSE - 0.5597357262879418
R_squared - 0.5882730401141985

In [13]:
import joblib

joblib.dump(lr, "linear_model.pkl")
print("Model saqlandi")

Model saqlandi

In [6]:
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train, y_train)

lasso_val_pred = lasso_model.predict(X_val)

print(f"MAE - {mean_absolute_error(y_val, lasso_val_pred)}")
print(f"RMSE - {root_mean_squared_error(y_val, lasso_val_pred)}")
print(f"MSE - {mean_squared_error(y_val, lasso_val_pred)}")
print(f"R_squared - {r2_score(y_val, lasso_val_pred)}")

MAE - 0.6044884300075902
RMSE - 0.8115024516742287
MSE - 0.6585362290732839
R_squared - 0.5155979744778281

In [7]:
ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train, y_train)

ridge_val_pred = ridge_model.predict(X_val)

print(f"MAE - {mean_absolute_error(y_val, ridge_val_pred)}")
print(f"RMSE - {root_mean_squared_error(y_val, ridge_val_pred)}")
print(f"MSE - {mean_squared_error(y_val, ridge_val_pred)}")
print(f"R_squared - {r2_score(y_val, ridge_val_pred)}")

MAE - 0.5442944060508722
RMSE - 0.7481620102569972
MSE - 0.5597463935917912
R_squared - 0.5882651935244994

In [8]:
elas_net_model = ElasticNet(alpha=0.1, l1_ratio=0.5)
elas_net_model.fit(X_train, y_train)

elas_net_pred = elas_net_model.predict(X_val)

print(f"MAE - {mean_absolute_error(y_val, elas_net_pred)}")
print(f"RMSE - {root_mean_squared_error(y_val, elas_net_pred)}")
print(f"MSE - {mean_squared_error(y_val, elas_net_pred)}")
print(f"R_squared - {r2_score(y_val, elas_net_pred)}")

MAE - 0.5668891792114541
RMSE - 0.7748325848565204
MSE - 0.600365534555437
R_squared - 0.5583868158603738

In [9]:
data = {
    "Model": ['Linear', 'Ridge', 'Lasso', 'ElasticNet'],
    "R_squared": [
        r2_score(y_val, lr_val_pred),
        r2_score(y_val, ridge_val_pred),
        r2_score(y_val, lasso_val_pred),
        r2_score(y_val, elas_net_pred),
        ],
    "MAE": [
        mean_absolute_error(y_val, lr_val_pred),
        mean_absolute_error(y_val, ridge_val_pred),
        mean_absolute_error(y_val, lasso_val_pred),
        mean_absolute_error(y_val, elas_net_pred),
    ]
}

df = pd.DataFrame(data)
df

        Model  R_squared       MAE
0      Linear   0.588273  0.544293
1       Ridge   0.588265  0.544294
2       Lasso   0.515598  0.604488
3  ElasticNet   0.558387  0.566889

In [10]:
test_pred = lr.predict(test)
test['Med_House_Val'] = test_pred
test

,id,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Med_House_Val
0,37137,1.7062,35.0,4.966368,1.096539,1318.0,2.844411,39.75,-121.85,0.445160
1,37138,1.3882,22.0,4.187035,1.098229,2296.0,3.180218,33.95,-118.29,1.143455
2,37139,7.7197,21.0,7.129436,0.959276,1535.0,2.888889,33.61,-117.81,3.569639
3,37140,4.6806,49.0,4.769697,1.048485,707.0,1.743590,34.17,-118.34,2.813132
4,37141,3.1284,25.0,3.765306,1.081633,4716.0,2.003827,34.17,-118.29,1.955788
...,...,...,...,...,...,...,...,...,...,...
24754,61891,2.2875,34.0,3.914729,1.085271,866.0,2.071429,34.44,-119.75,2.163588
24755,61892,3.0781,33.0,4.771971,1.038674,1628.0,2.326848,34.09,-117.96,1.733795
24756,61893,2.6961,14.0,4.593960,1.170380,3900.0,2.540034,37.51,-120.83,1.328738
24757,61894,7.2315,8.0,7.508403,1.018692,1388.0,2.601202,33.67,-117.98,3.275751
24758,61895,5.7260,30.0,6.000000,1.000000,15.0,2.500000,37.96,-122.47,3.110225

In [96]:
submission = pd.DataFrame(
    test
)
submission.to_csv("test_results.csv", index=False)